name: My First Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "Hello, world!"

      - name: Test
        run: echo "Running tests..."

      - name: Deploy
        if: ${{ env.DEPLOYMENT }}
        run: echo "Deploying application..."