name: My First Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 5 * * 1-5'

jobs:
  my_job:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT: true

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Print a message
        run: echo "Hello, world!"

      - name: Set up Go
        uses: actions/setup-go@v4
            
      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          npm install
          npm test
          npm set-deployment

      - name: Deploy
        if: ${{ env.DEPLOYMENT }}
        run: |
          npm run deploy